import { useState } from 'react';
import { Shield } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { EntitySelector } from '@/components/permissions/EntitySelector';
import { PermissionCheckboxGrid } from '@/components/permissions/PermissionCheckboxGrid';
import { OverrideListItem } from '@/components/permissions/OverrideListItem';
import { useUserStore } from '@/stores/userStore';
import { getEntityTypeLabel } from '@/lib/permissions/entityHelpers';
import { toast } from 'sonner';
import type { UserGroup } from '@/lib/types';
import type { EntityType, PermissionAction, PermissionSet } from '@/lib/types/permission';

interface GroupPermissionsDialogProps {
  group: UserGroup | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

interface FormState {
  entityType: EntityType | null;
  scope: 'all' | 'specific';
  specificEntityIds: string[];
  permissions: Partial<PermissionSet>;
}

export function GroupPermissionsDialog({ group, open, onOpenChange }: GroupPermissionsDialogProps) {
  const permissionOverrides = useUserStore(state => state.permissionOverrides);
  const addPermissionOverride = useUserStore(state => state.addPermissionOverride);
  const deletePermissionOverride = useUserStore(state => state.deletePermissionOverride);

  const [formState, setFormState] = useState<FormState>({
    entityType: null,
    scope: 'all',
    specificEntityIds: [],
    permissions: {},
  });

  if (!group) return null;

  // Filter overrides for this group
  const groupOverrides = permissionOverrides.filter(o => o.groupId === group.id);

  // Entity type options
  const entityTypes: EntityType[] = ['projects', 'workflows', 'tasks', 'comments', 'user_management'];

  const resetForm = () => {
    setFormState({
      entityType: null,
      scope: 'all',
      specificEntityIds: [],
      permissions: {},
    });
  };

  const handleEntityTypeChange = (value: EntityType) => {
    setFormState({
      ...formState,
      entityType: value,
      scope: 'all',
      specificEntityIds: [],
    });
  };

  const handleScopeChange = (scope: 'all' | 'specific', selectedEntityIds: string[]) => {
    setFormState({
      ...formState,
      scope,
      specificEntityIds: selectedEntityIds,
    });
  };

  const handlePermissionChange = (action: PermissionAction, checked: boolean) => {
    setFormState({
      ...formState,
      permissions: {
        ...formState.permissions,
        [action]: checked,
      },
    });
  };

  const handleSubmit = () => {
    if (!formState.entityType) {
      toast.error('Please select an entity type');
      return;
    }

    const hasPermissions = Object.values(formState.permissions).some(p => p === true);
    if (!hasPermissions) {
      toast.error('Please select at least one permission');
      return;
    }

    addPermissionOverride({
      id: '', // Will be generated by store
      groupId: group.id,
      entityType: formState.entityType,
      scope: formState.scope,
      specificEntityIds: formState.specificEntityIds,
      permissions: formState.permissions,
    });

    toast.success('Permission override added', {
      description: `Override for ${getEntityTypeLabel(formState.entityType)} has been created.`,
    });

    resetForm();
  };

  const handleDelete = (overrideId: string) => {
    deletePermissionOverride(overrideId);
    toast.success('Permission override deleted');
  };

  const isFormValid = formState.entityType !== null && Object.values(formState.permissions).some(p => p === true);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[1200px] max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5" />
            Group Permissions
          </DialogTitle>
          <DialogDescription>
            Manage permission overrides for "{group.name}"
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 overflow-y-auto max-h-[calc(80vh-160px)]">
          {/* Left Column: Add Override Form */}
          <div className="space-y-4">
            <div>
              <h3 className="font-medium mb-3">Add Override</h3>
              <div className="space-y-4">
                {/* Entity Type Selector */}
                <div className="space-y-2">
                  <Label htmlFor="entity-type">Entity Type</Label>
                  <Select
                    value={formState.entityType || ''}
                    onValueChange={(value) => handleEntityTypeChange(value as EntityType)}
                  >
                    <SelectTrigger id="entity-type">
                      <SelectValue placeholder="Select entity type" />
                    </SelectTrigger>
                    <SelectContent>
                      {entityTypes.map(type => (
                        <SelectItem key={type} value={type}>
                          {getEntityTypeLabel(type)}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Entity Selector (Scope + Specific Entities) */}
                {formState.entityType && (
                  <div className="space-y-2">
                    <Label>Scope</Label>
                    <EntitySelector
                      entityType={formState.entityType}
                      scope={formState.scope}
                      selectedEntityIds={formState.specificEntityIds}
                      onChange={handleScopeChange}
                    />
                  </div>
                )}

                {/* Permission Checkboxes */}
                {formState.entityType && (
                  <div className="space-y-2">
                    <Label>Permissions</Label>
                    <PermissionCheckboxGrid
                      permissions={formState.permissions}
                      onChange={handlePermissionChange}
                    />
                  </div>
                )}

                {/* Submit Button */}
                <Button
                  onClick={handleSubmit}
                  disabled={!isFormValid}
                  className="w-full"
                >
                  Add Override
                </Button>
              </div>
            </div>
          </div>

          {/* Right Column: Existing Overrides List */}
          <div className="space-y-4">
            <div>
              <h3 className="font-medium mb-3">
                Existing Overrides ({groupOverrides.length})
              </h3>

              {groupOverrides.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-12 text-center border border-dashed rounded-lg">
                  <Shield className="h-12 w-12 text-muted-foreground mb-3" />
                  <p className="text-sm text-muted-foreground">
                    No permission overrides yet
                  </p>
                  <p className="text-xs text-muted-foreground mt-1">
                    Add an override using the form on the left
                  </p>
                </div>
              ) : (
                <div className="space-y-3">
                  {groupOverrides.map(override => (
                    <OverrideListItem
                      key={override.id}
                      override={override}
                      onDelete={() => handleDelete(override.id)}
                    />
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
